### ISSUE TITLE
incorrect plugin identifier

### ISSUE THREAD

**Issue by BertoTavira** [joepool/homebridge-cmdswitch2-no-logs#1]
Hi there and thanks for the plugin!

IDK if this project still alive (it should, it works great!) but I'm here basically because of this:

[24/03/2021, 12:44:35] Loaded plugin: homebridge-cmdswitch2-no-logs@0.3.6
[24/03/2021, 12:44:35] Plugin 'homebridge-cmdswitch2-no-logs' tried to register with an incorrect plugin identifier: 'homebridge-cmdswitch2'. Please report this to the developer!

homebridge told me to report it to the dev so here I am :)

**Comment by joepool** [comment]
Hi,
I am aware of this issue, fixing it will most likely cause more problems than it solves, the functionality of the plugin is not affected by the wrong identifier, however as I didn't write the original plugin and don't fully understand how it has been written, it would be more hassle than its worth to fix it.
This may be something I Iook to fix in the future.

However thanks for reporting this issue
